grpc:
  address: :8080
  max_receive_message_bytes: 64MiB
  max_send_message_bytes: 32MiB
mode: gateway
health:
  address: :8081
prometheus:
  enabled: true
  address: :9090
shutdown_timeout: 15s
forwarding:
  dns_refresh_interval: 1s
  max_fanout: 8
  routes:
  - store: primary
    target: dns:///engine-primary:8080
    tls:
      insecure: true
  - store: secondary
    target: dns:///engine-secondary:8080
    tls:
      insecure: true
  - store: sync-only
    target: dns:///engine-sync-only:8080
    tls:
      insecure: true
  - store: elasticsearch-sync
    target: dns:///engine-elasticsearch-sync:8080
    tls:
      insecure: true
  - store: elasticsearch-async
    target: dns:///engine-elasticsearch-async:8080
    tls:
      insecure: true
  - store: mongodb-sync
    target: dns:///engine-mongodb-sync:8080
    tls:
      insecure: true
  - store: mongodb-async
    target: dns:///engine-mongodb-async:8080
    tls:
      insecure: true
request:
  max_operations: 1000
