name: mongodb-sync
storage:
  driver: mongodb
  mongodb:
    metadata_field: __sink
    max_concurrent_writes: 64 # Per process; shared by Engine and Worker configuration.
    max_concurrent_groups: 16
    uri: mongodb://mongodb:27017/?replicaSet=rs0
