name: primary
storage:
  driver: opensearch
  search:
    endpoints:
    - http://opensearch:9200
kafka:
  brokers:
  - kafka:19092
  enabled: true
  partitions: 8
  replication_factor: 1
  topic:
    name: sink-production-mutations
  dead_letter:
    name: sink-production-mutations.dlq
