name: secondary
storage:
  driver: opensearch
  search:
    endpoints:
    - http://opensearch-secondary:9200
kafka:
  brokers:
  - kafka-secondary:19092
  enabled: true
  partitions: 8
  replication_factor: 1
  topic:
    name: sink-production-secondary-mutations
  dead_letter:
    name: sink-production-secondary-mutations.dlq
